# Generated by Django 4.2.15 on 2024-08-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=50)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
