version: '3.3'

services:
  django-app:
    build: ./model_integration
    network_mode: host
    container_name: django-app
    ports:
      - "8000:8000"

  node-api:
    build: ./node_conversion
    network_mode: host
    container_name: node-api
    ports:
      - "3000:3000"
    depends_on:
      - django-app

